### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by shivabitla**
## Purpose

* ...

## Does this introduce a breaking change?

```
[x ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Review by jeffstof — APPROVED** [review]

**Comment by jeffstof** [comment]
We need another approval

**Comment by Infinitecupcakes** [comment]
approved

**Comment by fob2000** [comment]
Jeff approved.

**Comment by Infinitecupcakes** [comment]
approved

**Review by Infinitecupcakes — APPROVED** [review]

**Review by fob2000 — APPROVED** [review]

**Pull request merged**
